name = "the whole pastel"
author = "KatTheFox"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "123ac66f08a063647d2df142bdc939ceaacd736b716e54af21b8416c522a4b33"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
