name = "the whole pastel"
author = "KatTheFox"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f63b93b292352666919352df328f535194bd44905348ccf1c2bd016457dd6dac"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
