name = "the whole pastel"
author = "KatTheFox"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a148d936752fb1fad367b0e0b894ed0b33474078979af02ba58944b2b74f8e1"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
