name = "the whole pastel"
author = "KatTheFox"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9bf70a1df970cfbff768cd280bd289cfc4ff5d80e6effeb38a0e2b531948ec1"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
