name = "the whole pastel"
author = "KatTheFox"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7625655f233de0ede36126998daa12d3b24c34d140fd3b01320afa7f4141a913"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
