name = "the whole pastel"
author = "KatTheFox"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d58467b666db9feac661506bd0c5fbb342e63f13bd61d3f415d1aee3ff144a90"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
